backbone: "ViT-B/16"
n_prompt_tokens_L: 8
n_prompt_tokens_V: 5
loss_type: "ce"
intrinsic_dim_L: 200
intrinsic_dim_V: 200
sigma: 1
seed: 42
bound: 0
batch_size: 32
popsize: 30
train_mode: true
budget: 120

dtd:
  test_every: 1

ucf101:
  test_every: 1

eurosat:
  test_every: 1

flower102:
  test_every: 1

pets:
  test_every: 1

food101:
  test_every: 1

aircraft:
  test_every: 1

caltech101:
  test_every: 1

SUN397:
  test_every: 1
imagenet:
  test_every: 1

imagenet-a:
  test_every: 1

imagenet-r:
  test_every: 1

imagenet-sketch:
  test_every: 1

imagenet-v2:
  test_every: 1

cars:
  test_every: 1

